version: 2.1
jobs:
  build:
    docker:
      - image: circleci/browser-tools@1.2.3

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "b8:20:1c:84:9e:98:73:4b:ef:66:9d:30:c9:01:55:e0"

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@129.213.154.31 "ls -lrt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
