version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Add any additional build steps as necessary

  ssh-into-server:
    docker:
      - image: ubuntu:20.04

    environment:
      SSH_KEY: $SSH_PRIVATE_KEY

    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Install OpenSSH client
          command: |
            apt-get update
            apt-get install -y openssh-client

      - run:
          name: Configure SSH
          command: |
            echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

      - run:
          name: SSH into Ubuntu20 Server
          command: |
            ssh -o StrictHostKeyChecking=no user@your-server-ip \<< EOF
              # Run the shell script on the server
              sh /path/to/your-script.sh
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - ssh-into-server:
          requires:
            - build-and-test
