version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      # Add SSH keys
      - add_ssh_keys:
          fingerprints:
            - "18:3d:67:c0:96:a6:b9:46:0e:3d:27:16:e9:93:81:ff"

      # Run shell script on remote server
      - run:
          name: Run shell script
          command: 
            ssh opc@132.145.159.252 "yes"
            

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
