version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "18:3d:67:c0:96:a6:b9:46:0e:3d:27:16:e9:93:81:ff"

      # Create the results directory
      - run:
          name: Create Results Directory
          command: 
            ssh -o StrictHostKeyChecking=no root@132.145.159.252
            mkdir -p /tmp/result
            mkdir -p /tmp/soap/soap_html_report
            mkdir -p /tmp/soap/imap_html_report
            mkdir -p /tmp/soap/lmtp_html_report
            mkdir -p /tmp/soap/pop_html_report

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: 
            ssh -o StrictHostKeyChecking=no root@132.145.159.252 
            "cd /home/opc/zm-load-testing; sh regression_load_test.sh"
       
   #  Generate CSV file from jtl input
      - run:
          name: Generate CSV file from jtl file
          command: 
             ssh -o StrictHostKeyChecking=no root@132.145.159.252 
             "cd /home/opc/zm-load-testing; sh jtl_to_csv_converter.sh"

      # Copy test artifacts to the results directory
      - run:
          name: Copy Test Artifacts
          command: |
            
            scp -r root@132.145.159.252:/tmp/results /tmp/result
          

      # Upload test artifacts
      - store_artifacts:
          path: /tmp/result
              
      - store_artifacts:
          path: /tmp/soap/soap_html_report

      - store_artifacts:
          path: /tmp/imap/imap_html_report

      - store_artifacts:
          path:  /tmp/lmtp/lmtp_html_report

      - store_artifacts:
          path: /tmp/pop/pop_html_report
          

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
