version: 2.1

jobs:
  ssh-into-server:
    executor: ssh-executor

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: SSH into server and run JMeter test
          command: |
            echo "$SSH_PRIVATE_KEY" 
            ssh -o StrictHostKeyChecking=no opc@132.145.159.252 \<< EOF
              # Run the JMeter test
               sudo su -
              sh /opt/Branch/zm-load-testing/reportGen/scripts/loadtest.sh -t generic-eas -w /opt/Branch/zm-load-testing
            EOF

executors:
  ssh-executor:
    docker:
      - image: ubuntu:20.04

workflows:
  version: 2
  build-and-test:
    jobs:
      - ssh-into-server

