version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      # Run shell script on remote server
      - run:
          name: Run shell script
          command: 
            ssh ubuntu@129.213.154.31 "sudo su -"

workflows:
  version: 2
  build:
    jobs:
      - build
