version: 2.1
executors:
  ssh-executor:
    docker:
      - image: circleci/python:3.9

workflows:
  version: 2
  build-and-test:
    jobs:
      - ssh-into-server:
          filters:
            branches:
              only: master

jobs:
  ssh-into-server:
    executor: ssh-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - add_ssh_keys:
          fingerprints:
            - "SHA256:ag9R5yddl5QD50T/w7gM+GlREUYs1bMEcQX8aYr0o7g"

      - run:
          name: SSH into Ubuntu 20 Server
          command: |
            ssh opc@132.145.159.252 \<< EOF
              # Run the shell script on the server
              sudo su -
              sh /opt/Branch/zm-load-testing/reportGen/scripts/loadtest.sh -t generic-eas -w /opt/Branch/zm-load-testing
            EOF
