version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "18:3d:67:c0:96:a6:b9:46:0e:3d:27:16:e9:93:81:ff"

      # Create the results directory
      - run:
          name: Create Results Directory
          command: 
            ssh -o StrictHostKeyChecking=no root@132.145.159.252
            mkdir -p /tmp/result

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: 
            ssh -o StrictHostKeyChecking=no root@132.145.159.252 
            "cd /opt/apache-jmeter-3.3/bin; sh jmeter.sh -n -Juser.classpath=/home/opc/zm-load-testing/src/build/jar/zjmeter.jar -t /home/opc/zm-load-testing/tests/generic/zsoap/zsoap.jmx -q /home/opc/zm-load-testing/config/env.prop -q /home/opc/zm-load-testing/tests/generic/zsoap/load_basic.prop -q /home/opc/zm-load-testing/tests/generic/zsoap/profiles/basic.prop -l /tmp/results/result.csv -e -o /tmp/result -jmeter.save.saveservice.thread_counts=true -Djmeter.save.saveservice.output_format=xml -q /home/opc/zm-load-testing/config/extras.txt"
 
  
        
      
      # Copy test artifacts to the results directory
      - run:
          name: Copy Test Artifacts
          command: |
            
            scp -r root@132.145.159.252:/tmp/result /tmp/result
      
      # Upload test artifacts
      - store_artifacts:
          path: /tmp/result
          

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
