version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "d6:9a:78:21:fa:94:d0:7e:11:9d:5e:92:c8:66:7e:09"

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: 
            ssh -o StrictHostKeyChecking=no ubuntu@129.213.154.31 "ls -lrt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
