version: 2.1
executors:
  ssh-executor:
    docker:
      - image: circleci/python:3.9

workflows:
  build-and-test:
    jobs:
      - ssh-into-server:
          filters:
            branches:
              only: master

jobs:
  ssh-into-server:
    executor: ssh-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - add_ssh_keys:
          fingerprints:
            - "your-ssh-key-fingerprint"

      - run:
          name: SSH into Ubuntu 20 Server
          command: |
            ssh user@your-server-ip \<< EOF
              # Run the shell script on the server
              sh /path/to/your-script.sh
            EOF
