version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "8e:49:d8:7c:fc:23:6f:fa:f1:73:a0:4c:99:48:30:50"

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: 
            ssh -o StrictHostKeyChecking=no ubuntu@129.213.154.31 "ls -lrt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
