version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client

      # Set up SSH key
      - add_ssh_keys:
          fingerprints:
            - "18:3d:67:c0:96:a6:b9:46:0e:3d:27:16:e9:93:81:ff"

      # Connect to remote server and run JMeter test
      - run:
          name: Run JMeter test on remote server
          command: 
            ssh -o StrictHostKeyChecking=no root@132.145.159.252 
            "cd /home/opc/Branch/zm-load-testing && sh reportGen/scripts/loadtest_3.sh -t generic-zsoap -w /opt/Branch/zm-load-testing"

      - run:
          name: Store results 
          command: cp /tmp/results.jtl /tmp/results

      - store_artifacts:
          path: /home/opc/Branch/zm-load-testing/result
          destination: test-results

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
